item {
  id: 1
  name: 'B48'
}

item {
  id: 2
  name: 'B4'
}

item {
  id: 3
  name: 'B1'
}

item {
  id: 4
  name: 'A11'
}

item {
  id: 5
  name: 'B25'
}

item {
  id: 6
  name: 'B22'
}

item {
  id: 7
  name: 'A8'
}

item {
  id: 8
  name: 'C-'
}

item {
  id: 9
  name: 'B34'
}

item {
  id: 10
  name: 'B10'
}

item {
  id: 11
  name: 'B8'
}

item {
  id: 12
  name: 'A98'
}

item {
  id: 13
  name: 'A55'
}

item {
  id: 14
  name: 'B27'
}

item {
  id: 15
  name: 'A15'
}

item {
  id: 16
  name: 'A19'
}

item {
  id: 17
  name: 'A20'
}

item {
  id: 18
  name: 'A33'
}

item {
  id: 19
  name: 'A5'
}

item {
  id: 20
  name: 'D-'
}

item {
  id: 21
  name: 'A57'
}

item {
  id: 22
  name: 'B44'
}

item {
  id: 23
  name: 'A31'
}

item {
  id: 24
  name: 'other'
}

item {
  id: 25
  name: 'B5'
}